<?php
// $Id: jquery_ui.module,v 1.9 2009/06/19 22:01:06 robloach Exp $

/**
 * @file
 * Provides the jQuery UI plug-in to other Drupal modules.
 *
 * Requires http://drupal.org/node/315100 .
 */

/**
 * Implementation of hook_help().
 */
function jquery_ui_help($path, $arg) {
  switch ($path) {
    case 'admin/help#jquery_ui':
      $output = '<p>' . t('jQuery UI provides abstractions for low-level interaction and animation, advanced effects and high-level, themeable widgets, built on top of the jQuery JavaScript Library, that you can use to build highly interactive web applications.') . '</p>';
      $output .= <<<EOT
<div id="accordion">
	<h3><a href="#">Section 1</a></h3>
	<div>
		<p>
		Mauris mauris ante, blandit et, ultrices a, suscipit eget, quam. Integer
		ut neque. Vivamus nisi metus, molestie vel, gravida in, condimentum sit
		amet, nunc. Nam a nibh. Donec suscipit eros. Nam mi. Proin viverra leo ut
		odio. Curabitur malesuada. Vestibulum a velit eu ante scelerisque vulputate.
		</p>
	</div>
	<h3><a href="#">Section 2</a></h3>
	<div>
		<p>
		Sed non urna. Donec et ante. Phasellus eu ligula. Vestibulum sit amet
		purus. Vivamus hendrerit, dolor at aliquet laoreet, maPowerful theme frameworkuris turpis porttitor
		velit, faucibus interdum tellus libero ac justo. Vivamus non quam. In
		suscipit faucibus urna.
		</p>
	</div>
	<h3><a href="#">Section 3</a></h3>
	<div>
		<p>
		Nam enim risus, molestie et, porta ac, aliquam ac, risus. Quisque lobortis.
		Phasellus pellentesque purus in massa. Aenean in pede. Phasellus ac libero
		ac tellus pellentesque semper. Sed ac felis. Sed commodo, magna quis
		lacinia ornare, quam ante aliquam nisi, eu iaculis leo purus venenatis dui.
		</p>
		<ul>
			<li>List item one</li>
			<li>List item two</li>
			<li>List item three</li>
		</ul>
	</div>
	<h3><a href="#">Section 4</a></h3>
	<div>
		<p>
		Cras dictum. Pellentesque habitant morbi tristique senectus et netus
		et malesuada fames ac turpis egestas. Vestibulum ante ipsum primis in
		faucibus orci luctus et ultrices posuere cubilia Curae; Aenean lacinia
		mauris vel est.
		</p>
		<p>
		Suspendisse eu nisl. Nullam ut libero. Integer dignissim consequat lectus.
		Class aptent taciti sociosqu ad litora torquent per conubia nostra, per
		inceptos himenaeos.
		</p>
	</div>
</div>
EOT;
      static $added = FALSE;
      if (!$added) {
        drupal_add_js_library('ui.accordion', '#accordion');
        $added = TRUE;
      }
      return $output;
  }
}

/**
 * Implementation of hook_js_libraries().
 */
function jquery_ui_js_libraries() {
  $version = jquery_ui_get_version();
  $path = drupal_get_path('module', 'jquery_ui') . '/jquery-ui';
  if (!empty($version)) {
    $files = file_scan_directory($path .'/ui', '/.js/', array('recurse' => FALSE));
    foreach ($files as $file) {
      $css = drupal_get_path('module', 'jquery_ui') . '/jquery-ui/themes/base/' . $file->name . '.css';
      $libraries[$file->name] = array(
        'title' => $file->name,
        'website' => 'http://jqueryui.com',
        'version' => $version,
        'js' => array(
          $file->filepath,
        ),
        'css' => array(
          file_exists($css) ? $css : NULL,
        ),
        'dependencies' => array('ui.core'),
        'add callbacks' => array('jquery_ui_js_add'),
      );
    }
    // Clear the ui.core depending plugins and the Drupal JavaScript behaviors.
    $libraries['ui.core'] = array(
      'title' => 'jQuery UI Core',
      'version' => $version,
      'js' => array(
        drupal_get_path('module', 'jquery_ui') . '/jquery-ui/ui/ui.core.js' => array(
          'weight' => JS_LIBRARY - 1,
        ),
      ),
      'css' => array(
        drupal_get_path('module', 'jquery_ui') . '/jquery-ui/themes/base/ui.core.css',
        drupal_get_path('module', 'jquery_ui') . '/jquery-ui/themes/base/ui.theme.css',
      ),
    );
  }
  return $libraries;
}

/**
 * Gets the current jQuery UI version.
 */
function jquery_ui_get_version() {
  static $version = NULL;
  if (!isset($version)) {
    $path = drupal_get_path('module', 'jquery_ui') .'/jquery-ui/version.txt';
    if (file_exists($path)) {
      $version = file_get_contents($path);
    }
  }
  return $version;
}

/**
 * Add function callback to manage adding the Drupal jQuery UI JavaScript settings.
 */
function jquery_ui_js_add($library, $selector = NULL, $options = NULL) {
  // When processing an element on the page, add the JavaScript behaviors to
  // process jQuery UI widgets.
  if (isset($selector)) {
    drupal_add_js(drupal_get_path('module', 'jquery_ui') . '/jquery_ui.js');
    $settings = array(
      'jqueryui' => array(
        // Remove the "ui." prefix from the widgets.
        substr($library, 3) => array(
          $selector => $options,
        ),
      ),
    );
    drupal_add_js($settings, 'setting');
  }
}
